#pragma once

#include "Math/AddNode.h"
#include "Math/ClampNode.h"
#include "Math/CrossNode.h"
#include "Math/DistanceNode.h"
#include "Math/DivideNode.h"
#include "Math/DotNode.h"
#include "Math/InterpolateNode.h"
#include "Math/LogNode.h"
#include "Math/MaxMinNode.h"
#include "Math/ModuloNode.h"
#include "Math/MultiplyNode.h"
#include "Math/PowNode.h"
#include "Math/ReflectNode.h"
#include "Math/RefractNode.h"
#include "Math/RotateAroundAxisNode.h"
#include "Math//RemapNode.h"

#include "Miscellaneous/CombineVectorNode.h"
#include "Miscellaneous/SimpleFunctionNodes.h"
#include "Miscellaneous/VectorComponentsNode.h"
#include "Miscellaneous/WhiteNoiseNode.h"

#include "Parameters/CameraDataNode.h"
#include "Parameters/MoreShaderInNodes.h"
#include "Parameters/ParamNode.h"
#include "Parameters/ShaderInNodes.h"
#include "Parameters/TextureSampleNode.h"
#include "Parameters/TimeNode.h"