#pragma once

#include "Math/AddNode.h"
#include "Math/ClampNode.h"
#include "Math/CrossNode.h"
#include "Math/DistanceNode.h"
#include "Math/DivideNode.h"
#include "Math/DotNode.h"
#include "Math/InterpolateNode.h"
#include "Math/LogNode.h"
#include "Math/MaxMinNode.h"
#include "Math/ModuloNode.h"
#include "Math/MultiplyNode.h"
#include "Math/PowNode.h"
#include "Math/ReflectNode.h"
#include "Math/RefractNode.h"
#include "Math/RotateAroundAxisNode.h"
#include "Math/RemapNode.h"
#include "Math/SubtractNode.h"

#include "Miscellaneous/CombineVectorNode.h"
#include "Miscellaneous/SwizzleNode.h"
#include "Miscellaneous/SimpleFunctionNodes.h"
#include "Miscellaneous/VectorComponentsNode.h"
#include "Miscellaneous/WhiteNoiseNode.h"
#include "Miscellaneous/LightingNode.h"
#include "Miscellaneous/DataNodeGenerators.h"

#include "Parameters/VertexInputNode.h"
#include "Parameters/VertexOutputNode.h"
#include "Parameters/ShaderComputationNodes.h"
#include "Parameters/CameraDataNode.h"
#include "Parameters/ProjectionDataNode.h"
#include "Parameters/ParamNode.h"
#include "Parameters/TextureSampleNode.h"
#include "Parameters/TimeNode.h"