#include "SimpleFunctionNodes.h"


MAKE_NODE_READABLE_CPP(SignNode, 1.0f)
MAKE_NODE_READABLE_CPP(CeilNode, 1.0f)
MAKE_NODE_READABLE_CPP(FloorNode, 1.0f)
MAKE_NODE_READABLE_CPP(AbsNode, 1.0f)
MAKE_NODE_READABLE_CPP(SineNode, 1.0f)
MAKE_NODE_READABLE_CPP(CosineNode, 1.0f)
MAKE_NODE_READABLE_CPP(InverseSineNode, 1.0f)
MAKE_NODE_READABLE_CPP(InverseCosineNode, 1.0f)
MAKE_NODE_READABLE_CPP(NormalizeNode, 1.0f)
MAKE_NODE_READABLE_CPP(FractNode, 1.0f)
MAKE_NODE_READABLE_CPP(OneMinusNode, 1.0f)
MAKE_NODE_READABLE_CPP(NegativeNode, 1.0f)