#include "SimpleFunctionNodes.h"


ADD_NODE_REFLECTION_DATA_CPP(SignNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(CeilNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(FloorNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(AbsNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(SineNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(CosineNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(InverseSineNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(InverseCosineNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(NormalizeNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(FractNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(OneMinusNode, 1.0f)
ADD_NODE_REFLECTION_DATA_CPP(NegativeNode, 1.0f)
