#pragma once

#include "../Materials/Data Nodes/ShaderGenerator.h"
#include "../Helper Classes/DrawingQuad.h"


//A static class that can generate commonly-used materials for the GUI system.
static class GUIMaterials : public ShaderGenerator
{
public:

    //Uniform parameters for the material generated by "GenerateQuadDrawMaterial()".
    static const std::string QuadDraw_Color, QuadDraw_Texture2D;
    //Generates a material that draws a texture multiplied by a vec4 color uniform.
    static ShaderGenerator::GeneratedMaterial GenerateQuadDrawMaterial(UniformDictionary & params,
                                                                       ShaderInOutAttributes vertexAttrs = DrawingQuad::GetAttributeData(),
                                                                       unsigned int vertexPosIndex = 0, unsigned int vertexUVIndex = 1);
};